####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -Wall
CFLAGS += -I. -I./classes -I./accessCSV
LIBS = -lpthread
NAME = main
ODIR = .
OBJ = o

OBJS = center.$(OBJ) \
	centersCSV.$(OBJ) \
	data.$(OBJ) \
	dataAnalysis.$(OBJ) \
	dataCollection.$(OBJ) \
	distanceCSV.$(OBJ) \
	distances.$(OBJ) \
	employee.$(OBJ) \
	employeesCSV.$(OBJ) \
	genetic.$(OBJ) \
	kMedoids.$(OBJ) \
	main.$(OBJ) \
	mission.$(OBJ) \
	missionsCSV.$(OBJ) \
	solution.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
VPATH = ./classes:./accessCSV

.c.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CXX) $(CFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
