####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CXXFLAGS = 
CXXFLAGS += -I. -I./classes -I./accessCSV
LIBS = 
NAME = main
ODIR = .
OBJ = o

OBJS = center.$(OBJ) \
	centersCSV.$(OBJ) \
	data.$(OBJ) \
	dataAnalysis.$(OBJ) \
	dataCollection.$(OBJ) \
	distanceCSV.$(OBJ) \
	distances.$(OBJ) \
	employee.$(OBJ) \
	employeesCSV.$(OBJ) \
	kMedoids.$(OBJ) \
	main.$(OBJ) \
	mission.$(OBJ) \
	missionsCSV.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
VPATH = ./classes:./accessCSV:./CMakeFiles/3.26.4/CompilerIdC:./CMakeFiles/3.26.4/CompilerIdCXX

.cpp.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CXX) $(CXXFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CXX) $(CXXFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
